"""add_audio_nas_path_to_videos

Revision ID: 2ff58888a65f
Revises: f2c7b1e4a8d3
Create Date: 2026-04-13 16:23:48.616354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff58888a65f'
down_revision: Union[str, Sequence[str], None] = 'f2c7b1e4a8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_articles_fts'), table_name='articles', schema='articles', postgresql_using='gin')
    op.create_index('idx_articles_fts', 'articles', [sa.literal_column("to_tsvector('english', headline || ' ' || body_text)")], unique=False, schema='articles', postgresql_using='gin')
    op.add_column('videos', sa.Column('audio_nas_path', sa.Text(), nullable=True), schema='youtube')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'audio_nas_path', schema='youtube')
    op.drop_index('idx_articles_fts', table_name='articles', schema='articles', postgresql_using='gin')
    op.create_index(op.f('idx_articles_fts'), 'articles', [sa.literal_column("to_tsvector('english'::regconfig, (headline || ' '::text) || body_text)")], unique=False, schema='articles', postgresql_using='gin')
    # ### end Alembic commands ###
